language: minimal

install:
    - sudo apt-get update
    - sudo apt-get install python-pip -y
    - sudo pip install docker-compose

script: docker-compose build

deploy:
    provider: script
    script: ./deploy.sh
    on:
        branch: master
