name: deploy-dockerhub
on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: cache-version-files
        uses: actions/cache@v2
        with:
          path: "$HOME/cache"
          key: ${{ github.event.repository.name }}-cache-${{ hashFiles('shadowsocks-libev/Changes') }}
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        env:
          DOCKERHUB_BUILD_TRIGGER: ${{ secrets.DOCKERHUB_BUILD_TRIGGER }}
        run: |
          pwd
          ls -alh
          cd ${{ github.repository }}
          ls -alh
          chmod +x deploy.sh
          ./deploy.sh
